more robust debian packaging (#127)

diff --git a/dev/lifecycle/debian b/dev/lifecycle/debian
--- a/dev/lifecycle/debian
+++ b/dev/lifecycle/debian
@@ -40,24 +40,84 @@ if [ ! "${TARGET_ARCHITECTURE}" ] ; then
   exit 1
 fi
 
+generate_manpage() {
+  mkdir -p ${DEB_SOURCES}/usr/share/man/man8
+
+  target_unit="${DEB_SOURCES}/usr/share/man/man8/vault-unit.8"
+  target_rest="${DEB_SOURCES}/usr/share/man/man8/vault-rest.8"
+
+  if [ -f ${target_unit} ] ; then
+    rm -f ${target_unit}
+  fi
+
+  if [ -f ${target_unit}.gz ] ; then
+    rm -f ${target_unit}.gz
+  fi
+
+  if [ -f ${target_rest} ] ; then
+    rm -f ${target_rest}
+  fi
+
+  if [ -f ${target_rest}.gz ] ; then
+    rm -f ${target_rest}.gz
+  fi
+
+cat > ${target_unit} <<EOL
+.TH VAULT-UNIT 8 2019 "Vault Unit" "OpenBank Account Vault Tenant Unit"
+.SH NAME
+vault \- starts openbank account vault account unit
+.SH DESCRIPTION
+The
+.B pldd
+vault rest provides REST server for accessing and manipulating vault units
+.EE
+EOL
+
+cat > ${target_rest} <<EOL
+.TH VAULT-REST 8 2019 "Vault REST" "OpenBank Account Vault REST Server"
+.SH NAME
+vault \- starts openbank account vault REST server
+.SH DESCRIPTION
+The
+.B pldd
+vault unit stores account journal and negotiates account balance blocation
+.EE
+EOL
+
+  cat ${target_unit} | gzip -n -9 > ${target_unit}.gz
+  rm ${target_unit}
+
+  cat ${target_rest} | gzip -n -9 > ${target_rest}.gz
+  rm ${target_rest}
+}
+
 generate_changelog() {
+  mkdir -p ${DEB_SOURCES}/usr/share/doc/vault
+
+  target="${DEB_SOURCES}/usr/share/doc/vault/changelog"
+
+  if [ -f ${target} ] ; then
+    rm -f ${target}
+  fi
+
+  if [ -f ${target}.Debian.gz ] ; then
+    rm -f ${target}.Debian.gz
+  fi
+
+  touch ${target}
+
   VER="${VERSION}"
   tag=HEAD
   ADDS=$(echo ${VER} | sed -e 's/~.*//' | cut -s -d- -f2 | sed '/^[[:space:]]*$/d')
-  if [ -f ${CHANGELOG} ] ; then
-    rm -f ${CHANGELOG}
-  fi
-
-  touch ${CHANGELOG}
 
   if [[ -z "${ADDS// }" ]] ; then
-    DATE=$(git log -1 --format=%cD ${tag})
-    echo "vault (${VER}) ${DIST}; urgency=low" >> ${CHANGELOG}
-    echo "" >> ${CHANGELOG}
-    echo "  * Includes non-released commits" >> ${CHANGELOG}
-    echo "" >> ${CHANGELOG}
-    echo " -- Jan Cajthaml <jan.cajthaml@gmail.com>  ${DATE}" >> ${CHANGELOG}
-    echo "" >> ${CHANGELOG}
+    DATE=$(date '+%a, %-d %b %Y %H:%M:%S %z')
+    echo "vault (${VER}) unstable; urgency=low" >> ${target}
+    echo "" >> ${target}
+    echo "  * includes non-released commits" >> ${target}
+    echo "" >> ${target}
+    echo " -- Jan Cajthaml <jan.cajthaml@gmail.com>  ${DATE}" >> ${target}
+    echo "" >> ${target}
   fi
 
   PAIRS=()
@@ -78,20 +138,23 @@ generate_changelog() {
 
     if [[ -n "${commits// }" ]] ; then
 
-      echo "vault (${tag_to#v}) ${DIST}; urgency=low" >> ${CHANGELOG}
-      echo "" >> ${CHANGELOG}
+      echo "vault (${tag_to#v}) stable; urgency=low" >> ${target}
+      echo "" >> ${target}
 
       echo "${commits}" | \
       while read note ; do
-        echo "  * $(tr '[:lower:]' '[:upper:]' <<< ${note:0:1})${note:1}" >> ${CHANGELOG}
+        echo "  * $(tr '[:lower:]' '[:upper:]' <<< ${note:0:1})${note:1}" >> ${target}
       done
 
-      echo "" >> ${CHANGELOG}
+      echo "" >> ${target}
 
-      echo " -- Jan Cajthaml <jan.cajthaml@gmail.com>  ${DATE}" >> ${CHANGELOG}
-      echo "" >> ${CHANGELOG}
+      echo " -- Jan Cajthaml <jan.cajthaml@gmail.com>  ${DATE}" >> ${target}
+      echo "" >> ${target}
     fi
   done
+
+  cat ${target} | gzip -n -9 > ${target}.Debian.gz
+  rm ${target}
 }
 
 ################################################################################
@@ -105,50 +168,86 @@ if [ ! -d "${DEB_SOURCES}" ] ; then
   exit 1
 fi
 
-CHANGELOG=${DEB_SOURCES}/DEBIAN/changelog
-CONTROL=${DEB_SOURCES}/DEBIAN/control
-DIST=unstable
-FIRST=1
+if [ ! -f "${BIN_SOURCES}/vault-rest-linux-${TARGET_ARCHITECTURE}" ] ; then
+  (>&2 echo "did not found binary to package at ${BIN_SOURCES}/vault-rest-linux-${TARGET_ARCHITECTURE}")
+  exit 1
+fi
 
 if [ ! -f "${BIN_SOURCES}/vault-unit-linux-${TARGET_ARCHITECTURE}" ] ; then
   (>&2 echo "did not found binary to package at ${BIN_SOURCES}/vault-unit-linux-${TARGET_ARCHITECTURE}")
   exit 1
 fi
 
-if [ ! -f "${BIN_SOURCES}/vault-rest-linux-${TARGET_ARCHITECTURE}" ] ; then
-  (>&2 echo "did not found binary to package at ${BIN_SOURCES}/vault-rest-linux-${TARGET_ARCHITECTURE}")
-  exit 1
+mkdir -p ${DEB_SOURCES}/usr/bin
+if [ -f "${DEB_SOURCES}/usr/bin/vault-rest" ] ; then
+  rm -f ${DEB_SOURCES}/usr/bin/vault-rest
+fi
+if [ -f "${DEB_SOURCES}/usr/bin/vault-unit" ] ; then
+  rm -f ${DEB_SOURCES}/usr/bin/vault-unit
 fi
 
-mkdir -p ${DEB_SOURCES}/openbank/services/vault
+case ${TARGET_ARCHITECTURE} in
 
-if [ -f "${DEB_SOURCES}/openbank/services/vault/vault-unit" ] ; then
-  rm -f ${DEB_SOURCES}/openbank/services/vault/vault-unit
-fi
+  armhf)
+    arm-linux-gnueabihf-objcopy \
+      --strip-debug \
+      --strip-unneeded \
+      "${BIN_SOURCES}/vault-rest-linux-${TARGET_ARCHITECTURE}" \
+      "${DEB_SOURCES}/usr/bin/vault-rest"
+    arm-linux-gnueabihf-objcopy \
+      --strip-debug \
+      --strip-unneeded \
+      "${BIN_SOURCES}/vault-unit-linux-${TARGET_ARCHITECTURE}" \
+      "${DEB_SOURCES}/usr/bin/vault-unit"
+  ;;
 
-if [ -f "${DEB_SOURCES}/openbank/services/vault/vault-rest" ] ; then
-  rm -f ${DEB_SOURCES}/openbank/services/vault/vault-rest
-fi
+  arm64)
+    aarch64-linux-gnu-objcopy \
+      --strip-debug \
+      --strip-unneeded \
+      "${BIN_SOURCES}/vault-rest-linux-${TARGET_ARCHITECTURE}" \
+      "${DEB_SOURCES}/usr/bin/vault-rest"
+    aarch64-linux-gnu-objcopy \
+      --strip-debug \
+      --strip-unneeded \
+      "${BIN_SOURCES}/vault-unit-linux-${TARGET_ARCHITECTURE}" \
+      "${DEB_SOURCES}/usr/bin/vault-unit"
+  ;;
 
-du -hs "${BIN_SOURCES}/vault-unit-linux-${TARGET_ARCHITECTURE}"
-du -hs "${BIN_SOURCES}/vault-rest-linux-${TARGET_ARCHITECTURE}"
+  amd64)
+    objcopy \
+      --strip-debug \
+      --strip-unneeded \
+      "${BIN_SOURCES}/vault-rest-linux-${TARGET_ARCHITECTURE}" \
+      "${DEB_SOURCES}/usr/bin/vault-rest"
+    objcopy \
+      --strip-debug \
+      --strip-unneeded \
+      "${BIN_SOURCES}/vault-unit-linux-${TARGET_ARCHITECTURE}" \
+      "${DEB_SOURCES}/usr/bin/vault-unit"
+  ;;
 
-cp \
-  "${BIN_SOURCES}/vault-unit-linux-${TARGET_ARCHITECTURE}" \
-  "${DEB_SOURCES}/openbank/services/vault/vault-unit"
+  *)
+    cp \
+      "${BIN_SOURCES}/vault-rest-linux-${TARGET_ARCHITECTURE}" \
+      "${DEB_SOURCES}/usr/bin/vault-unit"
+    cp \
+      "${BIN_SOURCES}/vault-rest-linux-${TARGET_ARCHITECTURE}" \
+      "${DEB_SOURCES}/usr/bin/vault-rest"
+  ;;
 
-cp \
-  "${BIN_SOURCES}/vault-rest-linux-${TARGET_ARCHITECTURE}" \
-  "${DEB_SOURCES}/openbank/services/vault/vault-rest"
-
-file "${DEB_SOURCES}/openbank/services/vault/vault-unit"
-file "${DEB_SOURCES}/openbank/services/vault/vault-rest"
+esac
 
 generate_changelog
-sed -i 's/Version.*/Version: '${VERSION#v}'/' ${CONTROL}
+generate_manpage
 
-find "${BIN_SOURCES}" -type f -name "vault_*_${TARGET_ARCHITECTURE}.deb" -exec rm {} \;
+sed -i 's/Version.*/Version: '${VERSION#v}'/' "${DEB_SOURCES}/DEBIAN/control"
+
+find "${BIN_SOURCES}" -name "vault_*_${TARGET_ARCHITECTURE}.deb" -exec rm -f {} \;
 
 dpkg-deb --build "${DEB_SOURCES}" "${BIN_SOURCES}"
 
+find "${BIN_SOURCES}" -name "vault_*_${TARGET_ARCHITECTURE}.deb" -exec fakeroot lintian --pedantic {} \;
 find "${BIN_SOURCES}" -name "vault_*_${TARGET_ARCHITECTURE}.deb" -exec du -hs {} \;
+
+exit 0
